sourcegridlabs.conf
server {
    listen 80;
    server_name sourcegridlabs.com www.sourcegridlabs.com;

    root /var/www/SourceGridLabs;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }

    error_page 404 /404.html;
}

server {
    listen 443 ssl default_server;
    listen [::]:443 ssl default_server;
    server_name sourcegridlabs.com www.sourcegridlabs.com;

    root /var/www/SourceGridLabs;
    index index.html;

    ssl_certificate /etc/letsencrypt/live/sourcegridlabs.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/sourcegridlabs.com/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    location / {
        try_files $uri $uri/ =404;
    }

    error_page 404 /404.html;
}